from typing import Protocol, List, Any, Optional, Dict

class ICombatView(Protocol):
    """Interface für die Haupt-Ansicht des Combat Trackers."""

    def setup_ui(self) -> None: ...

    def show_error(self, title: str, message: str) -> None: ...
    def show_info(self, title: str, message: str) -> None: ...
    def show_warning(self, title: str, message: str) -> None: ...
    def ask_yes_no(self, title: str, message: str) -> bool: ...

    def log_message(self, message: str) -> None: ...

    def update_listbox(self) -> None: ...

    def get_quick_add_data(self) -> Dict[str, Any]: ...
    def clear_quick_add_fields(self) -> None: ...
    def set_quick_add_defaults(self) -> None: ...

    def get_selected_char_id(self) -> Optional[str]: ...
    def highlight_character(self, char_id: str) -> None: ...

    def get_action_value(self) -> int: ...
    def get_action_type(self) -> str: ...

    def get_status_input(self) -> Dict[str, Any]: ... # status, rank, duration

    def update_round_label(self, round_number: int) -> None: ...

    def fill_input_fields(self, data: Dict[str, Any]) -> None: ...

    def update_colors(self, colors: Dict[str, str]) -> None: ...

    def focus_damage_input(self) -> None: ...
